package com.lyp.weservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.17
 * 2018-11-18T20:10:39.282+08:00
 * Generated source version: 3.1.17
 * 
 */
@WebService(targetNamespace = "http://weservice.lyp.com/", name = "HelloWorld")
@XmlSeeAlso({ObjectFactory.class})
public interface HelloWorld {

    @WebMethod
    @RequestWrapper(localName = "say", targetNamespace = "http://weservice.lyp.com/", className = "com.lyp.weservice.Say")
    @ResponseWrapper(localName = "sayResponse", targetNamespace = "http://weservice.lyp.com/", className = "com.lyp.weservice.SayResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.lang.String say(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );

    @WebMethod
    @RequestWrapper(localName = "getRole", targetNamespace = "http://weservice.lyp.com/", className = "com.lyp.weservice.GetRole")
    @ResponseWrapper(localName = "getRoleResponse", targetNamespace = "http://weservice.lyp.com/", className = "com.lyp.weservice.GetRoleResponse")
    @WebResult(name = "return", targetNamespace = "")
    public com.lyp.weservice.MyRoleArray getRole();

    @WebMethod
    @RequestWrapper(localName = "getRoleByUser", targetNamespace = "http://weservice.lyp.com/", className = "com.lyp.weservice.GetRoleByUser")
    @ResponseWrapper(localName = "getRoleByUserResponse", targetNamespace = "http://weservice.lyp.com/", className = "com.lyp.weservice.GetRoleByUserResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<com.lyp.weservice.Role> getRoleByUser(
        @WebParam(name = "arg0", targetNamespace = "")
        com.lyp.weservice.User arg0
    );
}
